In [1]:
import pandas as pd
import yfinance as yf

In [2]:
df_yahoo = yf.download('AAPL', start='2000-01-01', end='2024-12-31', progress=False)

In [3]:
df_yahoo.head()

Price      Adj Close     Close      High       Low      Open     Volume
Ticker          AAPL      AAPL      AAPL      AAPL      AAPL       AAPL
Date
2000-01-03  0.843077  0.999442  1.004464  0.907924  0.936384  535796800
2000-01-04  0.771997  0.915179  0.987723  0.903460  0.966518  512377600
2000-01-05  0.783293  0.928571  0.987165  0.919643  0.926339  778321600
2000-01-06  0.715509  0.848214  0.955357  0.848214  0.947545  767972800
2000-01-07  0.749401  0.888393  0.901786  0.852679  0.861607  460734400

In [4]:
df_yahoo.tail()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,AAPL,AAPL,AAPL,AAPL,AAPL,AAPL
Date,,,,,,
2024-12-23,255.270004,255.270004,255.649994,253.449997,254.770004,40858800
2024-12-24,258.200012,258.200012,258.209991,255.289993,255.490005,23234700
2024-12-26,259.019989,259.019989,260.100006,257.630005,258.190002,27237100
2024-12-27,255.589996,255.589996,258.700012,253.059998,257.829987,42355300
2024-12-30,252.199997,252.199997,253.500000,250.750000,252.229996,35557500

In [6]:
!pip install quandl

Collecting quandl
  Downloading Quandl-3.7.0-py2.py3-none-any.whl (26 kB)
Collecting inflection>=0.3.1
  Using cached inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Requirement already satisfied: requests>=2.7.0 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from quandl) (2.32.3)
Requirement already satisfied: python-dateutil in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from quandl) (2.9.0.post0)
Requirement already satisfied: pandas>=0.14 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from quandl) (2.2.2)
Requirement already satisfied: six in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from quandl) (1.16.0)
Requirement already satisfied: numpy>=1.8 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from quandl) (2.1.1)
Collecting more-itertools
  Downloading more_itertools-10.6.0-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: pytz>=2020.1 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from pandas>=0.14->quandl) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from pandas>=0.14->quandl) (2024.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (2024.8.30)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (3.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from requests>=2.7.0->quandl) (2.2.3)
Installing collected packages: more-itertools, inflection, quandl
Successfully installed inflection-0.5.1 more-itertools-10.6.0 quandl-3.7.0

[notice] A new release of pip available: 22.2.1 -> 25.0
[notice] To update, run: pip install --upgrade pip

In [7]:
import quandl

In [9]:
import numpy as np

In [8]:
df_yahoo = df_yahoo.loc[:, ['Adj Close']]
df_yahoo.rename(columns={'Adj Close': 'adj_close'}, inplace=True)

In [10]:
df_yahoo['simple_rtn'] = df_yahoo.adj_close.pct_change()
df_yahoo['log_rtn'] = np.log(df_yahoo.adj_close/df_yahoo.adj_close.shift())

In [11]:
df_yahoo.head()

Price      adj_close simple_rtn   log_rtn
Ticker          AAPL
Date
2000-01-03  0.843077        NaN       NaN
2000-01-04  0.771997  -0.084310 -0.088077
2000-01-05  0.783293   0.014633  0.014527
2000-01-06  0.715509  -0.086538 -0.090514
2000-01-07  0.749401   0.047368  0.046281

In [12]:
df_yahoo.tail()

Price        adj_close simple_rtn   log_rtn
Ticker            AAPL
Date
2024-12-23  255.270004   0.003065  0.003060
2024-12-24  258.200012   0.011478  0.011413
2024-12-26  259.019989   0.003176  0.003171
2024-12-27  255.589996  -0.013242 -0.013331
2024-12-30  252.199997  -0.013263 -0.013352

In [13]:
QUANDL_KEY='XaypSTHQ9JE4nNvnyz4E'
quandl.ApiConfig.api_key = QUANDL_KEY

In [14]:
df_all_dates = pd.DataFrame(index=pd.date_range(start='1999-12-31', end='2024-12-31'))

In [17]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.4-cp310-cp310-macosx_11_0_arm64.whl (9.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 961.0 kB/s eta 0:00:0000:01:010m
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from statsmodels) (2.2.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from statsmodels) (1.14.1)
Collecting patsy>=0.5.6
  Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.9/232.9 kB 1.1 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: numpy<3,>=1.22.3 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from statsmodels) (2.1.1)
Requirement already satisfied: packaging>=21.3 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: six>=1.5 in /Users/isaacoduh/.pyenv/versions/3.10.6/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-1.0.1 statsmodels-0.14.4

[notice] A new release of pip available: 22.2.1 -> 25.0
[notice] To update, run: pip install --upgrade pip

In [18]:
import pandas as pd
import numpy as np
import yfinance as yf
import seaborn as sns
import scipy.stats as scs
import statsmodels.api as sm
import statsmodels.tsa.api as smt

In [19]:
r_range = np.linspace(min(df_yahoo.log_rtn), max(df_yahoo.log_rtn), num=1000)
mu = df_yahoo.log_rtn.mean()
sigma = df_yahoo.log_rtn.std()
norm_pdf = scs.norm.pdf(r_range, loc=mu, scale=sigma)

In [20]:
df = yf.download('MSFT', start='2000-01-01', end='2024-12-31', progress=False)
df = df.loc[:,['Adj Close']]
df.rename(columns={'Adj Close': 'adj_close'}, inplace=True)

In [21]:
df['simple_rtn'] = df.adj_close.pct_change()
df['log_rtn'] = np.log(df.adj_close/df.adj_close.shift(1))

In [22]:
df.head()

Price       adj_close simple_rtn   log_rtn
Ticker           MSFT
Date
2000-01-03  35.864090        NaN       NaN
2000-01-04  34.652596  -0.033780 -0.034364
2000-01-05  35.017948   0.010543  0.010488
2000-01-06  33.844933  -0.033498 -0.034071
2000-01-07  34.287201   0.013067  0.012983

In [23]:
df = df_all_dates.join(df[['adj_close']], how='left').fillna(method='ffill').asfreq('M')

MergeError: Not allowed to merge between different levels. (1 levels on the left, 2 on the right)